### ISSUE TITLE
vacant seat in MEMBERS.md

### ISSUE THREAD

**Issue by andrewhsu** [moby/tsc#21]
@StefanScherer has recently joined Docker so that brings the number of Docker employees up to 3 out of 7 seats in [MEMBERS.md](https://github.com/moby/tsc/blob/4aaca93a4a38cdfc7222345a44726931a9a94ac4/MEMBERS.md).

According to the [README.md](https://github.com/moby/tsc/blob/3e6075e34d5887e2e1c7e9c7fa7bd79c12e99f8d/README.md):
> A single company cannot hold more than 1/3 (one-third) of the seats on the committee.

**Comment by estesp** [comment]
Yes, thanks for the reminder @andrewhsu. Stefan stepped down formally the day he joined Docker but the TSC has not formally started the process to replace his seat.
