### ISSUE TITLE
Extend the first TSC term until 01-31-2020 or 03-31-2020

### ISSUE THREAD

**Issue by AkihiroSuda** [moby/tsc#24]
https://github.com/moby/tsc/blob/master/MEMBERS.md

The first TSC has expired on 11-13-2019.
I suggest extending the first TSC term until they can set up the election for the next term.

@moby/tsc @moby/moby-maintainers

**Comment by cpuguy83** [comment]
Thanks @AkihiroSuda 

I agree this should be addressed sooner rather than later.

**Comment by thaJeztah** [comment]
SGTM, and agreed

**Comment by estesp** [comment]
I agree we need to address; it might be helpful (if at all possible) to get an understanding of what Docker, Inc. restructuring implies about the future of using the Moby umbrella for projects and/or any changes expected around how open source is organized given the lack of an enterprise product vs. project split? Not sure if @justincormack can provide any insight as I assume they will be figuring that out over the months ahead.

**Comment by yongtang** [comment]
@estesp +1, I think a scope of Moby/docker project would be very helpful.

**Comment by AkihiroSuda** [comment]
PR: https://github.com/moby/tsc/pull/25

**Comment by cpuguy83** [comment]
We need to deal with this again.

**Comment by AkihiroSuda** [comment]
Yes, and https://github.com/moby/tsc/issues/1 seems the blocker to reestablish TSC.

Also, I think we can also consider just substituting TSC with just moby/moby maintainers.

**Comment by AkihiroSuda** [comment]
cc @moby/tsc @moby/moby-maintainers
